fix: quirks in getOS & getArch (#54)
* cleanhouse: gitignore

* chore: modernize code & format

go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...

* fix: bad smell in code

handler/handler.go:71:10: Error return value of `w.Write` is not checked (errcheck)
                w.Write([]byte("OK"))
                       ^
handler/handler.go:182:10: Error return value of `w.Write` is not checked (errcheck)
                w.Write(b)
                       ^
handler/handler.go:199:9: Error return value of `w.Write` is not checked (errcheck)
        w.Write(buff.Bytes())
               ^
handler/handler.go:254:23: Error return value of `resp.Body.Close` is not checked (errcheck)
        defer resp.Body.Close()
                             ^
handler/handler_execute.go:205:23: Error return value of `resp.Body.Close` is not checked (errcheck)
        defer resp.Body.Close()
                             ^
handler/search.go:46:17: Error return value of `resp.Body.Close` is not checked (errcheck)
        resp.Body.Close()
                       ^
6 issues:
* errcheck: 6

* fix: quirks in getOS & getArch

The problem in functions getOS & getArch is:
1. difficult to maintain

2. lie intentionally (if os/arch cannot match known pattern, return <only god knows>/amd64).
this quirk not only makes https://github.com/jpillora/installer/blob/7a007f5a2d5bc773bd2f3dae5803d2468ddec595/handler/handler_execute.go#L142 essentially dead code,
but also makes the matching of linux/amd64 asset prune to interferences, since the regex pattern of linux/amd64 can easily matches wrong assets like linux/ppc64.
On the other hand, restricting the regex pattern will increase the ratio of mismatch. To conclude, it might be bad idea to hack the getOS & getArch functions.

This commit makes the following changes:

1. split the regex patterns, ease the maintenance

2. match more architectures. Even we do not support them now, it still helps in reducing the noise while matching for assets in linux/amd64

3. stop lying when encounter an unknown architecture, make the function more simple.
The logic of assuming assets with unknown architecure was temporary removed, and will be introduced back in the coming commits

* feat: assume assets with unknown architecure

* chore: more unit tests

* cleanhouse: simplify the test cases with wrap func makeTestRequest

* feat: more test cases

* fix: match arch pattern "x86"

* fix: guessed OS/arch not written to the candidates

chore: clearify when the guessing of OS will stop

* Revert "fix: bad smell in code"

This reverts commit 14d493c783056cd2c045b68a65cff7ea77abec39.

* chore: optimize performance